#! /bin/sh

#  ██
# ░██              ██████
# ░██       ██████░██░░░██ ███     ██ ██████████
# ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██
# ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██
# ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██
# ░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██
# ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░


#____________________ARRANQUE DEL SISTEMA_____________________

export PATH="$PATH:$(du "$HOME/.local/bin/modulos/" | cut -f2 | paste -sd ':' -)"
export EDITOR=nvim
pkill -9 polybar &
pgrep -x sxhkd > /dev/null
sxhkd &
pipewire &
pkill picom
picom --config /home/robert/.config/picom/picom.conf &
polybar bar &
pkill dunst
dunst -config ~/.config/dunst/dunstrc &
feh --bg-fill /home/robert/Pictures/Wallpapers/wall7.png &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
eval $(gnome-keyring-daemon -s -- components=pkcs11,secrets,ssh,gpg) &
xsetroot -cursor_name left_ptr &

#_______________CONFIGURACION DE 1 Y 2 MONITORES________________________

bspc monitor -d  一 二 三 四 五 六 七 八 九 零
# bspc monitor -d I II III IV V VI VII VIII IX X

#______________________BORDES Y COLORES/CONF BSPWM_______________________

bspc config border_width         1
bspc config window_gap           2
bspc config top_padding     		 0
bspc config bottom_padding    	 0
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config directional_focus_tightness low
bspc config merge_overlapping_monitors true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config automatic_scheme longest_side
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
#bspc config focused_frame_opacity 0.05
#bspc config normal_frame_opacity 1.0
#___________________ FullCOLOR Theme _______________________
bspc config urgent_border_color "#dd2727"
bspc config focused_border_color "#03B4CB"
bspc config presel_feedback_color "#FF492B"
#___________________ Black Theme ___________________________
#bspc config focused_border_color "#dddddd"
#bspc config presel_feedback_color "#FF492B"
#___________________ Dracula Theme __________________________
#bspc config focused_border_color "#FF79C6"
#bspc config presel_feedback_color "#8BE9FD"