local wezterm = require 'wezterm';
local act = wezterm.action
if wezterm.config_builder then
  config = wezterm.config_builder()
end
return {
    term = 'wezterm',
    font = wezterm.font_with_fallback ({
	{family="JetBrainsMono Nerd Font Mono", harfbuzz_features={"calt=1", "clig=1", "liga=1"}},
	"JetBrains Mono",
	"Noto Color Emoji",
	"Symbols Nerd Font Mono",
    }),
    font_size = 10,
    initial_rows = 24,
    initial_cols = 102,
    adjust_window_size_when_changing_font_size = true,
    hide_tab_bar_if_only_one_tab = true,
    tab_bar_at_bottom = true,
    use_fancy_tab_bar = false,
    switch_to_last_active_tab_when_closing_tab = true,
    show_new_tab_button_in_tab_bar = false,
    default_cursor_style = "BlinkingBlock",
    cursor_blink_ease_in = "Constant",
    cursor_blink_ease_out = "Constant",
    cursor_blink_rate = 500,
    enable_kitty_keyboard = true,
    default_prog = {"/usr/bin/fish", "-l"},
    warn_about_missing_glyphs = false,
    audible_bell = "Disabled",
    enable_wayland = true,
    color_scheme = 'Catppuccin Mocha',
    xcursor_theme ="Catppuccin-Mocha-Mauve-Cursors",
    window_background_opacity = 0.90,
    keys = {
      {key="c", mods="CTRL|ALT", action=act{CopyTo="ClipboardAndPrimarySelection"}},
      {key="v", mods="CTRL|ALT", action=act{PasteFrom="PrimarySelection"}},
      {key="t", mods="SHIFT|ALT", action=act{SpawnTab="CurrentPaneDomain"}},
      {key="%", mods="CTRL|SHIFT|ALT", action=act.SplitHorizontal{domain="CurrentPaneDomain"}},
      {key="t", mods="CTRL|SUPER", action=act{SpawnTab="CurrentPaneDomain"}},
      {key="t", mods="CTRL|SUPER|ALT", action=act.CloseCurrentTab{confirm= true}},
      {key="1", mods="CTRL|SUPER", action=act{ActivateTab=0}},
      {key="2", mods="CTRL|SUPER", action=act{ActivateTab=1}},
      {key="3", mods="CTRL|SUPER", action=act{ActivateTab=2}},
      {key="4", mods="CTRL|SUPER", action=act{ActivateTab=3}},
      {key="5", mods="CTRL|SUPER", action=act{ActivateTab=4}},
      {key="6", mods="CTRL|SUPER", action=act{ActivateTab=5}},
      {key="7", mods="CTRL|SUPER", action=act{ActivateTab=6}},
      {key="8", mods="CTRL|SUPER", action=act{ActivateTab=7}},
      {key="9", mods="CTRL|SUPER", action=act{ActivateTab=8}},
      {key="0", mods="CTRL|SUPER", action=act{ActivateTab=9}},
      {key="-", mods="CTRL|SUPER|ALT", action=act{SplitVertical={domain="CurrentPaneDomain"}}},
      {key="|", mods="CTRL|SUPER", action=act{SplitHorizontal={domain="CurrentPaneDomain"}}},
      {key="-", mods="CTRL|SUPER", action=act.DecreaseFontSize},
      {key="+", mods="CTRL|SUPER", action=act.IncreaseFontSize},
      {key="c", mods="CTRL|SUPER", action=act.ResetFontSize},
      {key="h", mods="CTRL|SUPER", action=act{ActivatePaneDirection="Left"}},
      {key="l", mods="CTRL|SUPER", action=act{ActivatePaneDirection="Right"}},
      {key="j", mods="CTRL|SUPER", action=act{ActivatePaneDirection="Up"}},
      {key="k", mods="CTRL|SUPER", action=act{ActivatePaneDirection="Down"}},
      {key="h", mods="CTRL|SUPER|ALT", action=act{AdjustPaneSize={"Left", 1}}},
      {key="l", mods="CTRL|SUPER|ALT", action=act{AdjustPaneSize={"Right", 1}}},
      {key="j", mods="CTRL|SUPER|ALT", action=act{AdjustPaneSize={"Up", 1}}},
      {key="k", mods="CTRL|SUPER|ALT", action=act{AdjustPaneSize={"Down", 1}}},
      {key="p", mods="CTRL|SUPER|ALT", action=act.CloseCurrentPane {confirm= true}},
      {key="w", mods="CTRL|SUPER", action=act.SpawnWindow},
    },
    mouse_bindings = {
      {event={Up={streak=1, button="Right"}}, mods="NONE", action=wezterm.action{PasteFrom="PrimarySelection"}},
    },
}
