#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

[ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"
export TERM=xterm-256color

# Fzf
[[ ! -f /usr/share/fzf/key-bindings.bash ]] || source /usr/share/fzf/key-bindings.bash
[[ ! -f /usr/share/fzf/completion.bash ]] || source /usr/share/fzf/completion.bash
